"""Public Bids application contract."""
from typing import Any, Protocol

from backend.modules.deals.application.public_contract import Actor, CommandContext


class BidsApplication(Protocol):
    def create(self, payload: dict[str, Any], actor: Actor, context: CommandContext) -> Any: ...
    def update(self, bid_id: int, payload: dict[str, Any], actor: Actor, context: CommandContext) -> Any: ...
    def counter(self, bid_id: int, payload: dict[str, Any], actor: Actor, context: CommandContext) -> Any: ...
    def accept(self, bid_id: int, actor: Actor, context: CommandContext) -> Any: ...
    def reject(self, bid_id: int, actor: Actor, context: CommandContext) -> Any: ...
    def cancel(self, bid_id: int, actor: Actor, context: CommandContext) -> Any: ...
