const COPY = {
  RU: {
    myVehicles: 'Мои машины', addVehicle: 'Добавить машину', savedAccessibility: 'Данные машины успешно сохранены',
    step: 'Шаг', of: 'из', back: 'Назад', next: 'Продолжить →', save: 'Сохранить и продолжить →', saveOnly: 'Сохранить без публикации', retry: 'Повторить',
    basics: 'Основные данные', basicsSub: 'Укажите страну гражданства и страну регистрации вашего транспортного средства.', citizenship: 'Гражданство', registration: 'Страна регистрации транспортного средства', citizenshipSheet: 'Выберите гражданство', registrationSheet: 'Выберите страну регистрации ТС', search: 'Поиск страны',
    machine: 'Информация о машине', machineSub: 'Укажите характеристики вашего транспортного средства. Эти данные помогут подобрать подходящие грузы.', transport: 'Тип транспорта', body: 'Тип кузова / прицепа', make: 'Марка', model: 'Модель', plate: 'Госномер', payload: 'Грузоподъёмность (т)', volume: 'Объём (м³)', extra: 'Дополнительные параметры', optional: 'необязательно', length: 'Длина (м)', width: 'Ширина (м)', height: 'Высота (м)', select: 'Выберите', makeSheet: 'Выберите марку', modelSheet: 'Выберите модель',
    review: 'Проверьте и подтвердите', reviewSub: 'Проверьте данные. Вы всегда сможете изменить их в профиле.', edit: 'Изменить', documents: 'Документы можно добавить позже', documentsSub: 'Это не обязательно для публикации маршрута.', saveError: 'Не удалось сохранить данные', saveErrorSub: 'Проверьте подключение и попробуйте ещё раз.',
    success: 'Отлично!', successTitle: 'Ваша машина готова к работе!', successSub: 'Данные сохранены. Теперь вы можете публиковать маршруты, искать грузы и получать предложения.', publish: 'Перейти к публикации маршрута →', home: 'На главный экран', slogan: 'Вместе дальше!', findLoads: 'Ищите подходящие грузы', publishRoutes: 'Публикуйте маршруты', offers: 'Получайте предложения', safe: 'Работайте безопасно',
    sameCountry: 'Та же страна', noCountries: 'Не удалось загрузить список стран', invalid: 'Заполните все обязательные поля', loading: 'Сохранение…',
    types: { tractor_semitrailer: 'Тягач + полуприцеп', solo_truck: 'Одиночный грузовик', light_truck: 'Малотоннажный грузовик', road_train: 'Автопоезд', container_truck: 'Контейнеровоз', dump_truck: 'Самосвал', car_carrier: 'Автовоз', lowboy: 'Трал', tanker: 'Цистерна', other: 'Другое' },
    bodies: { curtain_sider: 'Тент', refrigerated: 'Рефрижератор', insulated: 'Изотерм', flatbed: 'Бортовой', container_platform: 'Контейнерная площадка', dump_body: 'Самосвальный кузов', tanker: 'Цистерна', lowboy: 'Трал', car_carrier: 'Автовоз', van: 'Фургон', other: 'Другое' },
    makes: { Volvo: 'Volvo', Mercedes_Benz: 'Mercedes-Benz', Scania: 'Scania', MAN: 'MAN', DAF: 'DAF', Iveco: 'Iveco', KAMAZ: 'КАМАЗ', HOWO: 'HOWO', FAW: 'FAW', Other: 'Другая марка' },
  },
  EN: {
    myVehicles: 'My vehicles', addVehicle: 'Add vehicle', savedAccessibility: 'Vehicle data saved successfully',
    step: 'Step', of: 'of', back: 'Back', next: 'Continue →', save: 'Save and continue →', saveOnly: 'Save without publishing', retry: 'Retry', basics: 'Basic information', basicsSub: 'Enter your citizenship and vehicle registration country.', citizenship: 'Citizenship', registration: 'Vehicle registration country', citizenshipSheet: 'Choose citizenship', registrationSheet: 'Choose vehicle registration country', search: 'Search country', machine: 'Vehicle information', machineSub: 'Enter your vehicle details to help match suitable loads.', transport: 'Vehicle type', body: 'Body / trailer type', make: 'Make', model: 'Model', plate: 'License plate', payload: 'Payload (t)', volume: 'Volume (m³)', extra: 'Additional parameters', optional: 'optional', length: 'Length (m)', width: 'Width (m)', height: 'Height (m)', select: 'Choose', makeSheet: 'Choose make', modelSheet: 'Choose model', review: 'Review and confirm', reviewSub: 'Check your data. You can always edit it in your profile.', edit: 'Edit', documents: 'Documents can be added later', documentsSub: 'They are not required to publish a route.', saveError: 'Could not save data', saveErrorSub: 'Check your connection and try again.', success: 'Great!', successTitle: 'Your vehicle is ready to work!', successSub: 'Your data is saved. You can now publish routes, find loads and receive offers.', publish: 'Go to publish route →', home: 'Home', slogan: 'Further together!', findLoads: 'Find suitable loads', publishRoutes: 'Publish routes', offers: 'Receive offers', safe: 'Work safely', sameCountry: 'Same country', noCountries: 'Could not load countries', invalid: 'Complete all required fields', loading: 'Saving…', types: { tractor_semitrailer: 'Tractor + semi-trailer', solo_truck: 'Rigid truck', light_truck: 'Light truck', road_train: 'Road train', container_truck: 'Container truck', dump_truck: 'Dump truck', car_carrier: 'Car carrier', lowboy: 'Lowboy', tanker: 'Tanker', other: 'Other' }, bodies: { curtain_sider: 'Curtain sider', refrigerated: 'Refrigerated', insulated: 'Insulated', flatbed: 'Flatbed', container_platform: 'Container platform', dump_body: 'Dump body', tanker: 'Tanker', lowboy: 'Lowboy', car_carrier: 'Car carrier', van: 'Van', other: 'Other' }, makes: { Volvo: 'Volvo', Mercedes_Benz: 'Mercedes-Benz', Scania: 'Scania', MAN: 'MAN', DAF: 'DAF', Iveco: 'Iveco', KAMAZ: 'KAMAZ', HOWO: 'HOWO', FAW: 'FAW', Other: 'Other make' },
  },
  ZH: {
    myVehicles: '我的车辆', addVehicle: '添加车辆', savedAccessibility: '车辆信息已成功保存',
    step: '第', of: '步', back: '返回', next: '继续 →', save: '保存并继续 →', saveOnly: '保存但不发布', retry: '重试', basics: '基本信息', basicsSub: '请选择您的国籍和车辆登记国家。', citizenship: '国籍', registration: '车辆登记国家', citizenshipSheet: '选择国籍', registrationSheet: '选择车辆登记国家', search: '搜索国家', machine: '车辆信息', machineSub: '填写车辆信息，帮助我们匹配合适的货物。', transport: '车辆类型', body: '车身 / 挂车类型', make: '品牌', model: '型号', plate: '车牌号', payload: '载重（吨）', volume: '体积（立方米）', extra: '其他参数', optional: '可选', length: '长度（米）', width: '宽度（米）', height: '高度（米）', select: '选择', makeSheet: '选择品牌', modelSheet: '选择型号', review: '请检查并确认', reviewSub: '请检查信息。您可以随时在个人资料中修改。', edit: '修改', documents: '文件可以稍后添加', documentsSub: '发布路线不需要这些文件。', saveError: '保存失败', saveErrorSub: '请检查网络连接后重试。', success: '太棒了！', successTitle: '您的车辆已准备就绪！', successSub: '信息已保存。现在可以发布路线、寻找货物并接收报价。', publish: '去发布路线 →', home: '首页', slogan: '一起走得更远！', findLoads: '寻找合适货物', publishRoutes: '发布路线', offers: '接收报价', safe: '安全工作', sameCountry: '同一国家', noCountries: '无法加载国家列表', invalid: '请填写所有必填项', loading: '正在保存…', types: { tractor_semitrailer: '牵引车+半挂车', solo_truck: '单车', light_truck: '轻型货车', road_train: '汽车列车', container_truck: '集装箱车', dump_truck: '自卸车', car_carrier: '轿运车', lowboy: '低平板车', tanker: '罐车', other: '其他' }, bodies: { curtain_sider: '篷布车', refrigerated: '冷藏车', insulated: '保温车', flatbed: '平板车', container_platform: '集装箱平板', dump_body: '自卸车厢', tanker: '罐式', lowboy: '低平板', car_carrier: '轿运车', van: '厢式车', other: '其他' }, makes: { Volvo: '沃尔沃', Mercedes_Benz: '奔驰', Scania: '斯堪尼亚', MAN: '曼恩', DAF: '达夫', Iveco: '依维柯', KAMAZ: '卡玛斯', HOWO: '豪沃', FAW: '一汽', Other: '其他品牌' },
  },
  KK: {
    myVehicles: 'Менің көліктерім', addVehicle: 'Көлік қосу', savedAccessibility: 'Көлік деректері сәтті сақталды',
    step: 'Қадам', of: 'ішінен', back: 'Артқа', next: 'Жалғастыру →', save: 'Сақтау және жалғастыру →', saveOnly: 'Жарияламай сақтау', retry: 'Қайталау', basics: 'Негізгі деректер', basicsSub: 'Азаматтығыңызды және көлік тіркелген елді көрсетіңіз.', citizenship: 'Азаматтық', registration: 'Көлік тіркелген ел', citizenshipSheet: 'Азаматтықты таңдаңыз', registrationSheet: 'Көлік тіркелген елді таңдаңыз', search: 'Елді іздеу', machine: 'Көлік туралы ақпарат', machineSub: 'Сәйкес жүктерді табу үшін көлік сипаттамаларын көрсетіңіз.', transport: 'Көлік түрі', body: 'Шанақ / тіркеме түрі', make: 'Маркасы', model: 'Моделі', plate: 'Мемлекеттік нөмір', payload: 'Жүк көтерімділігі (т)', volume: 'Көлемі (м³)', extra: 'Қосымша параметрлер', optional: 'міндетті емес', length: 'Ұзындығы (м)', width: 'Ені (м)', height: 'Биіктігі (м)', select: 'Таңдау', makeSheet: 'Марканы таңдаңыз', modelSheet: 'Модельді таңдаңыз', review: 'Тексеріңіз және растаңыз', reviewSub: 'Деректерді тексеріңіз. Оларды профильде өзгерте аласыз.', edit: 'Өзгерту', documents: 'Құжаттарды кейін қосуға болады', documentsSub: 'Олар маршрут жариялау үшін қажет емес.', saveError: 'Деректер сақталмады', saveErrorSub: 'Қосылымды тексеріп, қайталап көріңіз.', success: 'Керемет!', successTitle: 'Көлігіңіз жұмысқа дайын!', successSub: 'Деректер сақталды. Енді маршрут жариялап, жүк іздеп, ұсыныстар ала аласыз.', publish: 'Маршрут жариялауға өту →', home: 'Басты бет', slogan: 'Бірге алға!', findLoads: 'Сәйкес жүктерді іздеу', publishRoutes: 'Маршрут жариялау', offers: 'Ұсыныстар алу', safe: 'Қауіпсіз жұмыс', sameCountry: 'Сол ел', noCountries: 'Елдер тізімі жүктелмеді', invalid: 'Барлық міндетті жолдарды толтырыңыз', loading: 'Сақталуда…', types: { tractor_semitrailer: 'Тягач + жартылай тіркеме', solo_truck: 'Жеке жүк көлігі', light_truck: 'Шағын жүк көлігі', road_train: 'Автопойыз', container_truck: 'Контейнер тасымалдаушы', dump_truck: 'Самосвал', car_carrier: 'Автотасымалдаушы', lowboy: 'Трал', tanker: 'Цистерна', other: 'Басқа' }, bodies: { curtain_sider: 'Тент', refrigerated: 'Рефрижератор', insulated: 'Изотерм', flatbed: 'Бортты', container_platform: 'Контейнер алаңы', dump_body: 'Самосвал шанағы', tanker: 'Цистерна', lowboy: 'Трал', car_carrier: 'Автовоз', van: 'Фургон', other: 'Басқа' }, makes: { Volvo: 'Volvo', Mercedes_Benz: 'Mercedes-Benz', Scania: 'Scania', MAN: 'MAN', DAF: 'DAF', Iveco: 'Iveco', KAMAZ: 'КАМАЗ', HOWO: 'HOWO', FAW: 'FAW', Other: 'Басқа марка' },
  },
};

export const getVehicleCopy = (lang = 'RU') => COPY[lang] || COPY.EN;
