import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, Pressable, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Feather from '@expo/vector-icons/Feather';
import { storage } from '../../utils/storage';
import { regAPI } from '../../utils/registration';
import { vehicleAPI } from '../../utils/vehicleAPI';
import { useAuth } from '../../utils/AuthContext';
import { DRIVER_CERAMIC } from '../../theme/designV1Palette';
import DriverRouteBackdrop from '../../components/ui/v1/DriverRouteBackdrop';
import { useVehicleCopy, ProgressHeader, styles, countryLabel } from '../../components/vehicle/VehicleSetupUI';
const KEY = 'ur_vehicle_setup_draft';
export default function VehicleSetupReviewScreen({ navigation, route }) {
  const { lang, c } = useVehicleCopy(); const [d, setD] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const { setRole } = useAuth();
  useEffect(() => { storage.get(KEY).then((raw) => setD(JSON.parse(raw || '{}'))); }, []);
  const row = (key, value) => value ? <View style={styles.reviewRow}><Text style={styles.reviewKey}>{key}</Text><Text style={styles.reviewValue}>{value}</Text></View> : null;
  const save = async (publish) => { if (saving) return; setSaving(true); setError(''); const make = d.make === 'Other' ? d.make_custom : d.make; const payload = { vehicle_registration_country_code: d.vehicle_registration_country_code, vehicle_type: d.vehicle_type, body_type: d.body_type, make, model: d.model, license_plate: d.license_plate, payload_tons: Number(d.payload_tons), cargo_volume_m3: Number(d.cargo_volume_m3), cargo_length_m: d.cargo_length ? Number(d.cargo_length) : null, cargo_width_m: d.cargo_width ? Number(d.cargo_width) : null, cargo_height_m: d.cargo_height ? Number(d.cargo_height) : null }; const result = await vehicleAPI.save(payload); if (!result.ok) { setError(c.saveError); setSaving(false); return; } const draftSaved = await regAPI.saveDriverDraft({ citizenship_country: d.driver_citizenship_country_code, driver_citizenship_country_code: d.driver_citizenship_country_code, vehicle_registration_country: d.vehicle_registration_country_code, vehicle_registration_country_code: d.vehicle_registration_country_code, truck_kind: d.vehicle_type, vehicle_type: d.vehicle_type, body_type: d.body_type, vehicle_brand: make, vehicle_model: d.model, vehicle_plate: d.license_plate, capacity_tons: Number(d.payload_tons), volume_m3: Number(d.cargo_volume_m3) }); if (!draftSaved.ok) { setError(c.saveError); setSaving(false); return; } if (!publish) { const completed = await regAPI.completeBasic(); if (!completed.ok) { setError(c.saveErrorSub); setSaving(false); return; } setRole('driver'); } setSaving(false); if (!publish) { navigation.replace('Main', { role: 'driver' }); return; } navigation.replace('VehicleSetupSuccess', { vehicle: result.vehicle, publish, ...route?.params }); };
  return <SafeAreaView style={styles.safe} edges={['top', 'bottom']}><DriverRouteBackdrop /><ProgressHeader navigation={navigation} step={3} c={c} /><ScrollView contentContainerStyle={styles.scroll}><Text style={styles.title}>{c.review}</Text><Text style={styles.subtitle}>{c.reviewSub}</Text><View style={styles.reviewCard}><View style={styles.reviewHeader}><Feather name="user" size={22} color={DRIVER_CERAMIC.active} /><Text style={styles.reviewTitle}>{c.basics}</Text><Pressable onPress={() => navigation.navigate('VehicleSetupCountry', route?.params)}><Text style={styles.edit}>{c.edit}</Text></Pressable></View>{row(c.citizenship, countryLabel(d.driver_citizenship_country_code, lang))}{row(c.registration, countryLabel(d.vehicle_registration_country_code, lang))}</View><View style={styles.reviewCard}><View style={styles.reviewHeader}><Feather name="truck" size={22} color={DRIVER_CERAMIC.active} /><Text style={styles.reviewTitle}>{c.machine}</Text><Pressable onPress={() => navigation.navigate('VehicleSetupMachine', route?.params)}><Text style={styles.edit}>{c.edit}</Text></Pressable></View>{row(c.transport, c.types?.[d.vehicle_type])}{row(c.body, c.bodies?.[d.body_type])}{row(`${c.make} / ${c.model}`, `${d.make === 'Other' ? d.make_custom : c.makes?.[d.make]} ${d.model || ''}`)}{row(c.plate, d.license_plate)}{row(c.payload, d.payload_tons ? `${d.payload_tons} т` : '')}{row(c.volume, d.cargo_volume_m3 ? `${d.cargo_volume_m3} м³` : '')}{d.cargo_length && d.cargo_width && d.cargo_height ? row(`${c.length} × ${c.width} × ${c.height}`, `${d.cargo_length} × ${d.cargo_width} × ${d.cargo_height} м`) : null}</View>{error ? <><Text style={styles.error}>{error}</Text><Pressable testID="vehicle-setup-retry" disabled={saving} onPress={() => save(false)} style={styles.secondary}><Text style={styles.secondaryText}>{c.retry}</Text></Pressable></> : null}</ScrollView><View style={styles.footer}><Pressable disabled={saving} onPress={() => save(true)} style={[styles.cta, saving && styles.ctaDisabled]}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.ctaText}>{c.save}</Text>}</Pressable><Pressable disabled={saving} onPress={() => save(false)} style={styles.secondary}><Text style={styles.secondaryText}>{c.saveOnly}</Text></Pressable></View></SafeAreaView>;
}
